server:
  port: 7071

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zcrudtest
    username: root
    password: root
  jpa:
    hibernate:
    ddl-auto: update
    generate-ddl: true
    show-sql: true
    

#  application:
#    name: ZCRUD-USER-SERVICE

#eureka:
    #  instance:
    #prefer-ip-address: true
    #client:
    #fetch-registry: true
    #register-with-eureka: true
    #service-url:
    #defaultZne: http://localhost:8761/eureka
